<?php

namespace Fixture;

use Doctrine\Common\DataFixtures\AbstractFixture;
use Doctrine\Common\DataFixtures\DependentFixtureInterface;
use Doctrine\Common\Persistence\ObjectManager;
use Api\Sms\Entity\Sms;

class SmsData extends AbstractFixture implements DependentFixtureInterface
{
    public function load(ObjectManager $manager)
    {
        $sms = new Sms();
        $sms->setDdd('71');
        $sms->setNumber('91898583');
        $sms->setMessage('Message generated by unit test.');
        $sms->setSignature('Unit Test Controller');
        $sms->setStatus(Sms::SMS_STATUS_SENT);
        $sms->setType(Sms::SMS_TYPE_OUT);
        $sms->setCategory($this->getReference('user1_category1'));
        $sms->setGateway($this->getReference('conectta_gateway'));
        $manager->persist($sms);

        $sms2 = new Sms();
        $sms2->setDdd('71');
        $sms2->setNumber('91898583');
        $sms2->setMessage('Message test generated 1.');
        $sms2->setSignature('Unit Test Controller');
        $sms2->setStatus(Sms::SMS_STATUS_SENT);
        $sms2->setType(Sms::SMS_TYPE_OUT);
        $sms2->setCategory($this->getReference('user1_category1'));
        $sms2->setGateway($this->getReference('conectta_gateway'));
        $manager->persist($sms2);

        $sms3 = new Sms();
        $sms3->setDdd('71');
        $sms3->setNumber('91898583');
        $sms3->setMessage('Message test generated 2.');
        $sms3->setSignature('Unit Test Controller');
        $sms3->setStatus(Sms::SMS_STATUS_ERROR);
        $sms3->setType(Sms::SMS_TYPE_OUT);
        $sms3->setCategory($this->getReference('user1_category1'));
        $sms3->setGateway($this->getReference('zenvia_gateway'));
        $manager->persist($sms3);

        $sms4 = new Sms();
        $sms4->setDdd('71');
        $sms4->setNumber('88971306');
        $sms4->setMessage('Response message test generated 1.');
        $sms4->setSignature('Unit Test Controller');
        $sms4->setStatus(Sms::SMS_STATUS_SENT);
        $sms4->setType(Sms::SMS_TYPE_IN);
        $sms4->setCategory($this->getReference('user1_category1'));
        $sms4->setGateway($this->getReference('conectta_gateway'));
        $sms4->setSms($sms);
        $manager->persist($sms4);

        $sms5 = new Sms();
        $sms5->setDdd('71');
        $sms5->setNumber('91853435');
        $sms5->setMessage('Response message test generated 2.');
        $sms5->setSignature('Unit Test Controller');
        $sms5->setStatus(Sms::SMS_STATUS_SENT);
        $sms5->setType(Sms::SMS_TYPE_IN);
        $sms5->setCategory($this->getReference('user1_category1'));
        $sms5->setGateway($this->getReference('conectta_gateway'));
        $sms5->setSms($sms);
        $manager->persist($sms5);

        $manager->flush();

        $this->addReference('user1_sms_send', $sms);
        $this->addReference('user1_sms_success', $sms2);
        $this->addReference('user1_sms_error', $sms3);
        $this->addReference('user1_sms_response1', $sms4);
        $this->addReference('user1_sms_response2', $sms5);
    }

    public function getDependencies()
    {
        return ['Fixture\CategoryData', 'Fixture\GatewayData'];
    }
}